### ISSUE TITLE
Replace custom editorconfig parser by the new API context.Options.AnalyzerConfigOptionsProvider.GetOptions

### ISSUE THREAD

**Issue by meziantou** [meziantou/Meziantou.Analyzer#153]
The new Roslyn API `context.Options.AnalyzerConfigOptionsProvider.GetOptions` allows to get the configuration from the editorconfig file.

- [ ] Remove the custom editorconfig parser
- [ ] Replace all usage by `context.Options.AnalyzerConfigOptionsProvider.GetOptions`
- [ ] Update tests
- [ ] Update documentation to use the new names
- [ ] Update <https://github.com/meziantou/editorconfig/blob/master/.editorconfig>

**Comment by louis-z** [comment]
Hey @meziantou,

I started looking into this. I did a quick first pass where I
- kept `AnalyzerOptionsExtensions`
- got rid of all other `src/Meziantou.Analyzer/Configurations/` files
- adapted `AnalyzerOptionsExtensions` so that it calls `AnalyzerConfigOptionsProvider.GetOptions`. 

Manual tests seem to indicate that it's working, but some of the automated tests (you guessed it: those where you "inject" .editorconfig content) do not. Not sure yet if there is a way to inject such data in `AnalyzerConfigOptionsProvider`... 🤔

**Comment by meziantou** [comment]
From the Roslyn repository, it seems possible to set the analyzer options using `solution.AddAnalyzerConfigDocument`. https://github.com/dotnet/roslyn/blob/2f510ce51a222f618e85a5084683ea41d1a70db2/src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/CSharpCodeRefactoringVerifier%601%2BTest.cs#L42
