### ISSUE TITLE
New rule: Use Dictionary.TryGetValue instead of Dictionary.ContainsKey followed by a lookup

### ISSUE THREAD

**Issue by Paramethod** [meziantou/Meziantou.Analyzer#184]
I never wrote an analyzer, so I am not certain of what is possible api-wise, but I think this perf rule could be useful:

When the dictionary value is a reference type and a ContainsKey is followed by a lookup:
```
            // Two lookups...
            if (dic.ContainsKey("key"))
            {
                Poco poco = dic["key"];
            }
```
It should suggest the use of TryGetValue:
```
            // Single lookup
            if (dic.TryGetValue("key",out Poco poco))
            {

            }
```

**Comment by meziantou** [comment]
Everything's possible :)

The rule has already been suggested in the .NET repository dotnet/runtime#33798 and will be probably available in Microsoft.CodeAnalysis.FxCopAnalyzers in a few weeks/months. I don't want to implement a rule that is available in FxCop or will be available in this analyzer because it would just be duplicated work.
