### ISSUE TITLE
Not valid parameter name reported when parameter.property is used for ArgumentNullException(nameof(parameter.property))

### ISSUE THREAD

**Issue by dgvives** [meziantou/Meziantou.Analyzer#217]
**Context**
Rule identifier:  MA0015
Target Framework:  .NET Standard 2.0
Language version:  7.3

**Describe the bug**
Not valid parameter name reported when `throw new ArgumentNullException(nameof(parameter.property))`

**To Reproduce**

````c#
using System;

namespace TesterConsoleApp
{
    public static class TestProgram
    {
        public static void Main()
        {
            var p1 = new TestClass();

            Function1(p1);
        }

        private static void Function1(TestClass testclass)
        {
            if (testclass == null)
            {
                throw new ArgumentNullException(nameof(testclass));
            }

            if (testclass.testMember == null)
            {
                throw new ArgumentNullException(nameof(testclass.testMember));
            }
        }

        private class TestClass
        {
            public int? testMember;
        }
    }
}
````

**Additional context**
This is not a common use case, so it might not qualify as a bug but expected behaviour.

**Comment by meziantou** [comment]
This is the expected behavior. MA0015 validates that the value used for the parameter "paramName" is the name of one of the containing method parameters.

In this case, the method has one parameter named "testclass". `nameof(testclass.testMember)` is rewritten to `"testMember"` by the compiler. This value doesn't correspond to a parameter name. => report diagnostic MA0015.

Maybe the rule should allow "testclass.testMember" (i.e. `nameof(testclass) + '.' + nameof(testclass.testMember)`). But, I don't think it should allow "testMember".

**Comment by dgvives** [comment]
Agreed

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dgvives** [comment]
_Edit: earlier on mobile_

Current behaviour is expected behaviour. Analyzer was right, code under analysis not so much
This has been some sort of rubber ducking exercise. 
Thanks for your prompt answer and for this fine contribution

David
