### ISSUE TITLE
Do not warn `MA0155` for methods which get subscribed to an event

### ISSUE THREAD

**Issue by RenderMichael** [meziantou/Meziantou.Analyzer#714]
For the analyzer [`MA0155 - Do not use async void methods`](https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0155.md):

It would be nice if this rule did not fire when a method gets subscribed to an event, like so:
![image](https://github.com/meziantou/Meziantou.Analyzer/assets/12619902/454771f2-71e6-4230-9a0f-4018b2884bf6)

**Comment by meziantou** [comment]
Implementing this would change the way the analyzer is implemented. You cannot report any diagnostic before analyzing the full compilation. This decreases the dev experience as you may see warnings after a few seconds instead of instantaneous. Also, I don't know if Roslyn has fixed the issue with diagnostics reported at the end of the compilation. In the past, they were not visible in the editor, only in the error window and the CLI.

So, I'm not planning to implement this change yet.
